
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:membership
#    username: user
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


springdoc:
  swagger-ui:
    path: /swagger-ui.html
